import os
from datetime import datetime, timedelta, timezone

import bcrypt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from sqlalchemy.orm import Session

from app.crud.user import get_user_by_id
from app.database.database import get_db


# ============================================================
# JWT CONFIGURATION
# ============================================================

SECRET_KEY = os.getenv("JWT_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "JWT_SECRET_KEY is not configured."
    )

ALGORITHM = "HS256"

ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

# Used to identify tokens generated by this application.
TOKEN_TYPE = "access"


# ============================================================
# SECURITY CONFIGURATION
# ============================================================

security = HTTPBearer(
    auto_error=False,
)


# ============================================================
# AUTHENTICATION ERROR
# ============================================================

def authentication_error() -> HTTPException:
    """
    Return one consistent authentication error.

    The same message is used for malformed, expired,
    invalid, and user-less tokens to avoid leaking
    authentication details.
    """

    return HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid or expired authentication token.",
        headers={
            "WWW-Authenticate": "Bearer",
        },
    )


# ============================================================
# PASSWORD HASH
# ============================================================

def hash_password(password: str) -> str:
    """
    Hash a password using bcrypt.

    bcrypt has a practical 72-byte password limit, so
    enforce the limit before hashing rather than allowing
    truncation/ambiguous behavior.
    """

    if not isinstance(password, str):
        raise ValueError(
            "Password must be a string."
        )

    password_bytes = password.encode("utf-8")

    if len(password_bytes) > 72:
        raise ValueError(
            "Password is too long."
        )

    if len(password_bytes) == 0:
        raise ValueError(
            "Password cannot be empty."
        )

    return bcrypt.hashpw(
        password_bytes,
        bcrypt.gensalt(),
    ).decode("utf-8")


# ============================================================
# VERIFY PASSWORD
# ============================================================

def verify_password(
    plain_password: str,
    hashed_password: str,
) -> bool:
    """
    Safely verify a plaintext password against a bcrypt hash.
    """

    if not isinstance(plain_password, str):
        return False

    if not isinstance(hashed_password, str):
        return False

    password_bytes = plain_password.encode("utf-8")

    # bcrypt only supports passwords up to 72 bytes.
    if len(password_bytes) > 72:
        return False

    try:
        return bcrypt.checkpw(
            password_bytes,
            hashed_password.encode("utf-8"),
        )

    except (
        ValueError,
        TypeError,
    ):
        return False

# ============================================================
# CREATE ACCESS TOKEN
# ============================================================

def create_access_token(
    user_id: int,
) -> str:
    """
    Create a short-lived JWT access token.
    """

    if not isinstance(user_id, int) or user_id <= 0:
        raise ValueError(
            "Invalid user ID."
        )

    now = datetime.now(timezone.utc)

    expire = now + timedelta(
        minutes=ACCESS_TOKEN_EXPIRE_MINUTES,
    )

    payload = {
        "sub": str(user_id),
        "type": TOKEN_TYPE,
        "iat": now,
        "exp": expire,
    }

    return jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM,
    )


# ============================================================
# GET CURRENT USER
# ============================================================

def get_current_user(
    credentials: HTTPAuthorizationCredentials | None = Depends(
        security
    ),
    db: Session = Depends(get_db),
):
    """
    Validate the Bearer token and return the authenticated user.
    """

    credentials_exception = authentication_error()

    # --------------------------------------------------------
    # CHECK AUTHORIZATION HEADER
    # --------------------------------------------------------

    if credentials is None:
        raise credentials_exception

    # --------------------------------------------------------
    # CHECK AUTHENTICATION SCHEME
    # --------------------------------------------------------

    if credentials.scheme.lower() != "bearer":
        raise credentials_exception

    token = credentials.credentials

    if not token or len(token) > 4096:
        raise credentials_exception

    # --------------------------------------------------------
    # DECODE JWT
    # --------------------------------------------------------

    try:
        payload = jwt.decode(
            token,
            SECRET_KEY,
            algorithms=[ALGORITHM],
        )

    except JWTError:
        raise credentials_exception

    # --------------------------------------------------------
    # VALIDATE TOKEN TYPE
    # --------------------------------------------------------

    token_type = payload.get("type")

    if token_type != TOKEN_TYPE:
        raise credentials_exception

    # --------------------------------------------------------
    # GET USER ID FROM TOKEN
    # --------------------------------------------------------

    user_id = payload.get("sub")

    if not isinstance(user_id, str):
        raise credentials_exception

    # --------------------------------------------------------
    # CONVERT USER ID
    # --------------------------------------------------------

    try:
        parsed_user_id = int(user_id)

    except (TypeError, ValueError):
        raise credentials_exception

    if parsed_user_id <= 0:
        raise credentials_exception

    # --------------------------------------------------------
    # FIND USER
    # --------------------------------------------------------

    user = get_user_by_id(
        db=db,
        user_id=parsed_user_id,
    )

    if user is None:
        raise credentials_exception

    return user

